# Agent Zero Startup Script
# Author: Generated by nekomata-engineer

param(
    [switch]$Install,      # Install dependencies
    [switch]$Update,       # Update dependencies
    [switch]$Help          # Show help
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$VenvPath = Join-Path $ProjectRoot ".venv"
$VenvPython = Join-Path $VenvPath "Scripts\python.exe"
$RequirementsFile = Join-Path $ProjectRoot "requirements.txt"

# Colors for output
function Write-Info { param($msg) Write-Host "[INFO] $msg" -ForegroundColor Cyan }
function Write-Success { param($msg) Write-Host "[OK] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Err { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }

# Show help
function Show-Help {
    Write-Host ""
    Write-Host "Agent Zero Startup Script" -ForegroundColor Magenta
    Write-Host "=========================" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "Usage: .\start.ps1 [options]"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -Install    Create venv and install dependencies"
    Write-Host "  -Update     Update dependencies from requirements.txt"
    Write-Host "  -Help       Show this help message"
    Write-Host ""
    Write-Host "Examples:"
    Write-Host "  .\start.ps1              # Start Agent Zero"
    Write-Host "  .\start.ps1 -Install     # First time setup"
    Write-Host "  .\start.ps1 -Update      # Update packages"
    Write-Host ""
}

# Check if uv is available
function Test-UvInstalled {
    try {
        $null = Get-Command uv -ErrorAction Stop
        return $true
    } catch {
        return $false
    }
}

# Check if venv exists
function Test-VenvExists {
    return (Test-Path $VenvPython)
}

# Create virtual environment
function Initialize-Venv {
    if (-not (Test-VenvExists)) {
        Write-Info "Creating virtual environment..."
        if (Test-UvInstalled) {
            uv venv $VenvPath --python 3.12
        } else {
            python -m venv $VenvPath
        }
        Write-Success "Virtual environment created."
    } else {
        Write-Info "Virtual environment already exists."
    }
}

# Install dependencies
function Install-Dependencies {
    Write-Info "Installing dependencies..."
    Set-Location $ProjectRoot
    if (Test-UvInstalled) {
        # Use uv with explicit venv path
        uv pip install -r $RequirementsFile --python $VenvPython
    } else {
        # Use venv's pip directly
        & $VenvPython -m pip install -r $RequirementsFile
    }
    Write-Success "Dependencies installed."
}

# Main execution
function Start-AgentZero {
    Write-Host ""
    Write-Host "  ___                    _     ______               " -ForegroundColor Cyan
    Write-Host " / _ \                  | |    |___  /               " -ForegroundColor Cyan
    Write-Host "/ /_\ \ __ _  ___ _ __ | |_      / / ___ _ __ ___   " -ForegroundColor Cyan
    Write-Host "|  _  |/ _` |/ _ \ '_ \| __|    / / / _ \ '__/ _ \  " -ForegroundColor Cyan
    Write-Host "| | | | (_| |  __/ | | | |_   ./ /_|  __/ | | (_) | " -ForegroundColor Cyan
    Write-Host "\_| |_/\__, |\___|_| |_|\__| \_____/\___|_|  \___/  " -ForegroundColor Cyan
    Write-Host "        __/ |                                        " -ForegroundColor Cyan
    Write-Host "       |___/                                         " -ForegroundColor Cyan
    Write-Host ""

    # Check venv exists
    if (-not (Test-VenvExists)) {
        Write-Err "Virtual environment not found!"
        Write-Warn "Run '.\start.ps1 -Install' first."
        exit 1
    }

    Write-Info "Starting Agent Zero..."
    Write-Info "Project path: $ProjectRoot"
    Write-Info "Python: $VenvPython"
    Write-Host ""

    Set-Location $ProjectRoot

    # Use uv run or direct venv python
    if (Test-UvInstalled) {
        Write-Info "Using uv run..."
        uv run --python $VenvPython python run_ui.py
    } else {
        Write-Info "Using venv python directly..."
        & $VenvPython run_ui.py
    }
}

# Entry point
if ($Help) {
    Show-Help
    exit 0
}

if ($Install) {
    Write-Info "Running first time setup..."
    Initialize-Venv
    Install-Dependencies
    Write-Success "Setup complete! Run .\start.ps1 to start Agent Zero."
    exit 0
}

if ($Update) {
    if (-not (Test-VenvExists)) {
        Write-Err "Virtual environment not found! Run -Install first."
        exit 1
    }
    Install-Dependencies
    Write-Success "Dependencies updated!"
    exit 0
}

# Default: Start the application
Start-AgentZero
